### ISSUE TITLE
Is the ODS source data still current?

### ISSUE THREAD

**Issue by kevwhitt-nhs** [open-ods/open-ods#191]
Hi Matt

I notice that NHS Digital have finally released their own ODS API. I was wondering whether you are still keeping the data behind this one up to date and whether you plan to continue to make it available. i.e. should we be planning to switch to use the official one?

Thanks

**Comment by mattstibbs** [comment]
Hi Kevin,

It’s on my list to update the data but I am considering retiring this in light of NHS Digital’s API (which was built on top of OpenODS anyway). I think you may be the only regular user now - how do you feel about moving across to use theirs?

Matt

**Comment by kevwhitt-nhs** [comment]
I'm happy to move across in principle but I'm finding it a struggle in practice. My preferred method for calling the API is JavaScript / jQuery but I can't do this because their server doesn't allow X origin requests. I tried moving to code-behind calls to avoid the browser x-origin issues but the ODS API actively refuses my connection when I do it that way. My Exeter Helpdesk call on the issue was pretty much dismissed without being resolved, which was frustrating...

**Comment by mattstibbs** [comment]
Data updated to August 18 version.

**Comment by kevinkuszyk** [comment]
Hello @kevwhitt-nhs and @mattstibbs,

I've recently joined the team at NHS Digital who run our version of this API.

@kevwhitt-nhs are you still having issue consuming the NHSD version?  If yes, feel free to drop me a line at kevin.kuszyk@nhs.net and let's see what we can work out for you.

Best,

Kevin (K).
