### ISSUE TITLE
Add content negotiation

### ISSUE THREAD

**Issue by mattstibbs** [open-ods/open-ods#22]

**Comment by paulfurley** [comment]
Hey @mattstibbs can you elaborate? Are you wanting to serve a HTML version and a JSON version, for example? Is what would the default be?

(I've just done a *very* basic implementation of this over at https://github.com/greendragonsoft/ssldump.com/pull/18 so I could probably help)

**Comment by mattstibbs** [comment]
@paulfurley yes I was thinking just simple HTML and JSON to start with just so that it gives people a HTML representation of the entities when using a browser. 

I thought default should probably be `application/json` but not wed to that if you think the opposite works better

Any help very much appreciated :)

**Comment by mattstibbs** [comment]
Not needed
