### ISSUE TITLE
Add full-text searching

### ISSUE THREAD

**Issue by mattstibbs** [open-ods/open-ods#6]
We need to support proper full-text searching on the API. 

Currently the only search capability is achieved using a SQL like statement.

Note: It might be that to support full-text searching we might be better off implementing a different type of datastore more suited to text searching than SQL is (e.g. Elasticsearch)

**Comment by TimCoates** [comment]
Might be able to deliver this by using Solr / Lucene. Will refresh my memory / have a play with it.

**Comment by mattstibbs** [comment]
@TimCoates Great - I did find a file-based store somewhere (will try dig out the link) which looked like it might work and make deployment simple too. I only have experience in Elasticseach (which uses Lucene also) but am open to any suggestions that can deliver this whilst keeping it simple.
