### ISSUE TITLE
Add postcode search functionality

### ISSUE THREAD

**Issue by kevwhitt-nhs** [open-ods/open-ods#72]
We would like to use the provide a user interface in our application to allow users to lookup their ODS code for the Information Sharing Gateway (online Information Sharing Agreement / IG system). Organisation name can be tricky as a search term "Dalton Square Surgery" won't return any results since it's in ODS as "Dalton Square Practice", postcode searching will help in such cases.

Thanks

**Comment by mattstibbs** [comment]
1. Add a new query parameter for '?postcode=LS21'

2. Perform select query using parameter value as partial string match against postcode field in 'addresses' table

**Need to work out how to do query - maybe select addresses and map back to organisations**
