### ISSUE TITLE
Include 'status' field on organisation list

### ISSUE THREAD

**Issue by kevwhitt-nhs** [open-ods/open-ods#73]
When hitting the api with a [search for Blackpool Borough Council](http://www.openods.co.uk/api/organisations?q=blackpool+borough&recordClass=HSCOrg). Two results are returned (325 and V213). I can't see a way of omitting Inactive results (V213) without querying the API for each result and checking the detailed response. It would be good if either a query parameter could be passed to omit inactive results or the response to the search query included the status (active or inactive).

**Comment by mattstibbs** [comment]
Thanks for raising this. Firstly I'm quite impressed that the multi-word search worked as I didn't think it was working! :)

I should think we could do something like only returning active records by default, but allowing a parameter to be passed in to include inactive records.

When retrieving an [individual organisation](http://www.openods.co.uk/api/organisations/V213), there is a status field, but clearly this doesn't help you when just doing an organisation search.

**Comment by mattstibbs** [comment]
1. Update /organisations so that only active records are returned by default
2. Provide a query parameter that can be passed in which will include inactive results

**Comment by mattstibbs** [comment]
@kevwhitt-nhs started to look at this tonight, but noticed that V213 is coming up as Active.. 

Is it maybe one of its roles that you are seeing as Inactive?

Either way this doesn't negate the need to do something about the filtering... :)

**Comment by mattstibbs** [comment]
Added 'status' field to /organisations response so that clients can filter results themselves.

New issue raised: #74

**Comment by kevwhitt-nhs** [comment]
@mattstibbs thanks for looking into this. I may well be misreading the status. What I would like to do is filter out organisations that are listed as "Closed" (such as V213) when [searching the ODS Portal](https://odsportal.hscic.gov.uk/Organisation/Search?Name=blackpool%20borough%20council&FromPOST=True).  When I look at the full API JSON for [325](http://www.openods.co.uk/api/organisations/325) and [V213](http://www.openods.co.uk/api/organisations/V213) it's clear that V213 has an "operationalEndDate" and that 325 is listed as it's successor, otherwise, I'm not sure what marks it out as "Closed".
Thanks for your help with this. ODS codes are going to be fundamentally important in building our own API in the ISG to allow sharing platforms to interrogate it to check that an ISA is in place to govern data flows between organisations before data is released. Your API is going to be a key enabler for this work.

**Comment by mattstibbs** [comment]
Hi @kevwhitt-nhs - having looked at this a bit more closely, I can see that in fact both 325 and V213 are still technically 'Active' as organisations in the data.

The Technical Specification defines that the status of an organisation remains Active until it at least has an Operational End Date (and if the Legal Dates are different, a Legal End Date too).

Therefore, the data is technically saying both of these records are still active, as they are both missing an Operational End Date meaning that they are still 'Operational'.

I guess the next question will be whether this is a) correct and b) whether there is some other **reliable** inference we can make from the data regarding whether the organisation is still 'Open' as you have put it.

**Comment by kevwhitt-nhs** [comment]
Thanks  @mattstibbs. The ODS portal has V213 listed as "closed" when you search it, as per [here](https://odsportal.hscic.gov.uk/Organisation/Search?Name=blackpool%20borough%20council&FromPOST=True). It's organisations with that "closed" state that I would like to omit from results.  Not sure if this is possible?

**Comment by mattstibbs** [comment]
Name updated to reflect change actually made.

**Comment by mattstibbs** [comment]
@kevwhitt-nhs New release tonight - give it a go. Main thing is ?postCode=AB1+2DF parameter

**Comment by kevwhitt-nhs** [comment]
Thanks @mattstibbs. Not sure I'm getting the postcode API query syntax right: http://www.openods.co.uk/api/organisations?postcode=LA9+7RG returns several results but none correct (University Hospitals of Morecambe Bay NHS FT). When I vary the postcode, all the same results are returned whatever I type..? Thanks again.

**Comment by mattstibbs** [comment]
@kevwhitt-nhs I'm sure you'll say "pfft" to this, but the parameter key is case-sensitive so postCode needs a capital 'C'

Should probably fix that in future!

**Comment by kevwhitt-nhs** [comment]
Amazing!  I should have been more observant when looking at your example. Working perfectly now. Since I only need to teach a system to use it, it really doesn't matter about changing it - systems are a lot less prone to error than I am.

**Comment by mattstibbs** [comment]
You should be able to do it just on outcode too i.e. postCode=AB1
