### ISSUE TITLE
Provide openods api over https 

### ISSUE THREAD

**Issue by kevwhitt-nhs** [open-ods/open-ods#81]
We are trying to interrogate the API from a site that exclusively uses https and because openods is on another domain and does not use https, we cannot access. Is there any intention to provide over https?

**Comment by mattstibbs** [comment]
@kevwhitt-nhs Hasn't been a priority until now, but it really should be a a baseline expectation nowadays - so let's get it fixed :) Would you drop me an email to matt@openods.co.uk and we can chat about it properly :)

**Comment by mattstibbs** [comment]
api.openods.co.uk now served over https
