### ISSUE TITLE
Include organisation identifying information (pref postcode) in organisation search returns

### ISSUE THREAD

**Issue by kevwhitt-nhs** [open-ods/open-ods#84]
We are using calls like this:

http://api.openods.co.uk/api/organisations?q=king+street+surgery&recordClass=HSCOrg

To return possible organisation matches and asking users to select the correct one. Unfortunately, there is nothing in the search return other than organisation name and ODS code to identify the organisations. Including postcode would allow users to distinguish the correct result more easily. As a side, note, the link included in the results is to http://www.openods.co.uk/api/organisations/... when called from the above and doesn't currently work.

**Comment by mattstibbs** [comment]
Ok

On the incorrect link thing - yep I missed that so will get it sorted ASAP

On the search results thing that’s worth thinking about, there are a few options:

1. Just start returning full organisation records in the search results - this would be fine for low numbers but might be problematic if someone is asking for 1000 records to be returned.

2. Pick a few fields that people might want to include in results, and make it possible to specify which fields you want back when you make the request

Any thoughts? I could absolutely add postcode in for you as a stop gap but it would be good to think a bit more strategically about how to best serve the use case of someone using it as a search endpoint.

Matt

**Comment by kevwhitt-nhs** [comment]
You're right - selfishly, postcode works for us... but trying to look at the change from a broader perspective, I would be inclined to return the organisation record minus roles, relationships and successors linfo. This should keep big results lists sensible but provide enough info to work with?

**Comment by mattstibbs** [comment]
Yep - that might be the answer. The roles, successors, and relationships are the expensive parts of the query at the moment (although I have some ideas as to how I could optimise this in future if need be)

**Comment by mattstibbs** [comment]
The hyperlink issue should be fixed now…

**Comment by mattstibbs** [comment]
@kevwhitt-nhs As a way of solving your immediate need, would simply adding the postCode field to the /organisations results be enough?

**Comment by mattstibbs** [comment]
Never mind - did it anyway :) @kevwhitt-nhs 

postCode now returns in main /organisations results
