### ISSUE TITLE
R client?

### ISSUE THREAD

**Issue by dnbarron** [open-ods/open-ods#86]
Hi,

I'm thinking of working on an R client for OpenODS and wondered if you had any guidelines for what such a client should contain, or other clients that I could look at (I can see references to a couple of Issues related to clients, but I can't find the clients themselves).

David

**Comment by mattstibbs** [comment]
Hi @dnbarron!

I did originally intend to create some client libraries for OpenODS but a combination of time and lack of necessity means they never got anywhere... As I was mostly consuming from Python it was so easy to use the Requests library that I didn't feel a client would add a tremendous amount more.

Had I gone ahead though, I was intending to use it to provide a basic object model and easy filtering using the filters that are currently available. If you haven't seen it already, this is useful for understanding the filter parameters that can be passed in currently https://api.openods.co.uk/api/docs

I think ultimately the shape of the client needs to be driven by the use cases, and I have to admit I'm not familiar with R so not sure how this data might be consumed - however I will say that if you identify use cases that the API doesn't currently support particularly well just let me know and we can see if we can improve it!

Matt
